/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef RUNEI_API
#define RUNEI_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern RUNEI_API FName RUNEI_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class RUNEI_API AAccelerator : public AActor
{
public:
    DECLARE_CLASS(AAccelerator,AActor,0,RuneI)
    NO_DEFAULT_CONSTRUCTOR(AAccelerator)
};

#define UCONST_maxAdjacents 4

class RUNEI_API AMeshPoint : public AAccelerator
{
public:
    BITFIELD bAnchored:1 GCC_PACK(4);
    BITFIELD bDrawRopes:1;
    FLOAT SpringConstant GCC_PACK(4);
    FLOAT DampFactor;
    FLOAT MaxVelocityPickup;
    FName AdjacentTag[4];
    class AMeshPoint* Adjacent[4];
    FVector OriginalPos;
    DECLARE_FUNCTION(execMeshPointTick);
    DECLARE_CLASS(AMeshPoint,AAccelerator,0,RuneI)
    NO_DEFAULT_CONSTRUCTOR(AMeshPoint)
};

#define UCONST_MaximumVelocityPickup 500

class RUNEI_API ATreePoint : public AAccelerator
{
public:
    BITFIELD bHooker:1 GCC_PACK(4);
    BITFIELD bRestrictVelocity:1;
    BITFIELD bAffectsParent:1;
    BITFIELD bDrawRope:1;
    FLOAT MaxVelocityAllowed GCC_PACK(4);
    FLOAT GravAccel;
    FLOAT DampFactor;
    FName ParentTag;
    BITFIELD bApplyAcceleration:1 GCC_PACK(4);
    BITFIELD bStiffRotation:1;
    BITFIELD bSpring:1;
    FLOAT SpringConstant GCC_PACK(4);
    BITFIELD bApplySway:1 GCC_PACK(4);
    FVector SwayDir GCC_PACK(4);
    FLOAT SwayMagnitude;
    class USound* WhileMoving;
    class USound* HitAWall;
    class ATreePoint* Parent;
    BITFIELD bLeaf:1 GCC_PACK(4);
    FVector GravDir GCC_PACK(4);
    FLOAT BranchLength;
    class AActor* Attraction;
    class AActor* BeamActor;
    class AActor* hooked;
    FRotator hookOrientation;
    DECLARE_FUNCTION(execTreePointTick);
    DECLARE_CLASS(ATreePoint,AAccelerator,0,RuneI)
    NO_DEFAULT_CONSTRUCTOR(ATreePoint)
};


class RUNEI_API ASpringPoint : public AAccelerator
{
public:
    FLOAT SpringConstant;
    FLOAT DampFactor;
    FLOAT MaxVelocityPickup;
    FVector OriginalPos;
    DECLARE_FUNCTION(execSpringPointTick);
    DECLARE_CLASS(ASpringPoint,AAccelerator,0,RuneI)
    NO_DEFAULT_CONSTRUCTOR(ASpringPoint)
};


class RUNEI_API ARopePoint : public AAccelerator
{
public:
    FName NextTag;
    FName PrevTag;
    class ARopePoint* NextPoint;
    class ARopePoint* PrevPoint;
    BITFIELD bAnchored:1 GCC_PACK(4);
    FLOAT SpringConstant GCC_PACK(4);
    FLOAT DampFactor;
    FLOAT MaxVelocityPickup;
    FVector OriginalPos;
    DECLARE_FUNCTION(execRopePointTick);
    DECLARE_CLASS(ARopePoint,AAccelerator,0,RuneI)
    NO_DEFAULT_CONSTRUCTOR(ARopePoint)
};

#define UCONST_MaxConfiners 4

class RUNEI_API AConfinement : public AAccelerator
{
public:
    FLOAT MaxVelocityPickup;
    FName ConfinerTag[4];
    class AActor* Confiner[4];
    DECLARE_FUNCTION(execConfinementTick);
    DECLARE_CLASS(AConfinement,AAccelerator,0,RuneI)
    NO_DEFAULT_CONSTRUCTOR(AConfinement)
};

#endif

AUTOGENERATE_FUNCTION(AMeshPoint,655,execMeshPointTick);
AUTOGENERATE_FUNCTION(ATreePoint,654,execTreePointTick);
AUTOGENERATE_FUNCTION(ASpringPoint,653,execSpringPointTick);
AUTOGENERATE_FUNCTION(ARopePoint,652,execRopePointTick);
AUTOGENERATE_FUNCTION(AConfinement,651,execConfinementTick);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
